version: 2
updates:
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
    groups:
      docs-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
    groups:
      workflows-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 99
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Berlin"
    versioning-strategy: auto
    allow:
      - dependency-type: "all"
    groups:
      poetry-dependencies:
        patterns:
          - "*"
