version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_name}}"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 99
    groups:
      ck-poetry-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_name}}/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
    groups:
      ck-workflows-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/{{cookiecutter.project_name}}/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
    groups:
      ck-github-actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
    groups:
      docs-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
    groups:
      workflows-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 99
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
