name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: ${{"{{"}} matrix.session {{"}}"}} ${{"{{"}} matrix.python {{"}}"}} / ${{"{{"}} matrix.os {{"}}"}}
    runs-on: ${{"{{"}} matrix.os {{"}}"}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.11", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.11", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.12", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.13", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.10", os: "ubuntu-latest", session: "tests" }
          - { python: "3.11", os: "ubuntu-latest", session: "tests" }
          - { python: "3.12", os: "ubuntu-latest", session: "tests" }
          - { python: "3.13", os: "ubuntu-latest", session: "tests" }
          - { python: "3.13", os: "windows-latest", session: "tests" }
          - { python: "3.13", os: "macos-latest", session: "tests" }
          - { python: "3.11", os: "ubuntu-latest", session: "typeguard" }
          - { python: "3.11", os: "ubuntu-latest", session: "xdoctest" }
          - { python: "3.11", os: "ubuntu-latest", session: "docs-build" }

    env:
      NOXSESSION: ${{"{{"}} matrix.session {{"}}"}}
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

{% if cookiecutter.dependency_manager_tool == "poetry" %}
      - name: Set up Python ${{"{{"}} matrix.python {{"}}"}}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{"{{"}} matrix.python {{"}}"}}

      - name: Upgrade pip
        run: |
          pip install -c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt pip
          pip --version

      - name: Upgrade pip in virtual environments
        shell: python
        run: |
          import os
          import pip

          with open(os.environ["GITHUB_ENV"], mode="a") as io:
              print(f"VIRTUALENV_PIP={pip.__version__}", file=io)

      - name: Install Poetry
        run: |
          pipx install --pip-args "-c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" poetry
          pipx inject poetry poetry-plugin-export
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args "-c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox
          pipx inject --pip-args "-c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox nox-poetry
          nox --version
{% else %}
      - name: Get uv version from constraints
        id: uv-version
        shell: pwsh
        run: |
          $UV_VERSION = (Get-Content .github/workflows/constraints.txt | Where-Object { $_ -match '^uv==' } | ForEach-Object { ($_ -split '==')[1] })
          echo "version=$UV_VERSION" >> $env:GITHUB_OUTPUT

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: {{ "${{ steps.uv-version.outputs.version }}" }}
          python-version: ${{"{{"}} matrix.python {{"}}"}}
{% endif %}

      - name: Compute pre-commit cache key
        if: matrix.session == 'pre-commit'
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import subprocess
          import sys

          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = {{ '"${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])' }}
          cmd = f'echo "result={result}" >> $GITHUB_OUTPUT'
          subprocess.run(cmd, shell=True)

      - name: Restore pre-commit cache
        uses: actions/cache@v4
        if: matrix.session == 'pre-commit'
        with:
          path: ~/.cache/pre-commit
          key: {{ "${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}" }}
          restore-keys: |
            {{ "${{ steps.pre-commit-cache.outputs.result }}-" }}

      - name: Run Nox
        run: |
{% if cookiecutter.dependency_manager_tool == "poetry" %}
          nox --python=${{"{{"}} matrix.python {{"}}"}}
{% else %}
          uvx --constraints "${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox --python=${{ "{{ matrix.python }}" }}
{% endif %}

      - name: Upload coverage data
        if: always() && matrix.session == 'tests'
        uses: "actions/upload-artifact@v4"
        with:
          name: coverage-data-${{"{{"}} matrix.os {{"}}"}}-${{"{{"}} matrix.python {{"}}"}}
          path: ".coverage.*"
          include-hidden-files: true

      - name: Upload documentation
        if: matrix.session == 'docs-build'
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

{% if cookiecutter.dependency_manager_tool == "poetry" %}
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: |
          pip install -c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args "-c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" poetry
          pipx inject poetry poetry-plugin-export
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args "-c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox
          pipx inject --pip-args "-c ${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox nox-poetry
          nox --version
{% else %}
      - name: Get uv version from constraints
        id: uv-version
        shell: pwsh
        run: |
          $UV_VERSION = (Get-Content .github/workflows/constraints.txt | Where-Object { $_ -match '^uv==' } | ForEach-Object { ($_ -split '==')[1] })
          echo "version=$UV_VERSION" >> $env:GITHUB_OUTPUT

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: {{ "${{ steps.uv-version.outputs.version }}" }}
          python-version: "3.11"
{% endif %}

      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-*
          merge-multiple: true

      - name: Combine coverage data and display human readable report
        run: |
{% if cookiecutter.dependency_manager_tool == "poetry" %}
          nox --session=coverage
{% else %}
          uvx --constraints "${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox --session=coverage
{% endif %}

      - name: Create coverage report
        run: |
{% if cookiecutter.dependency_manager_tool == "poetry" %}
          nox --session=coverage -- xml
{% else %}
          uvx --constraints "${{ "{{ github.workspace }}" }}/.github/workflows/constraints.txt" nox --session=coverage -- xml
{% endif %}

      # Need to fix coverage source paths for SonarCloud scanning in GitHub actions.
      # Replace root path with /github/workspace (mounted in docker container).
      - name: Override coverage source paths for SonarCloud
        run: |
          sed -i "s/<source><\/source>/<source>\/home\/runner\/work\/{{cookiecutter.project_name}}\/{{cookiecutter.project_name}}<\/source>/g" coverage.xml
          sed -i "s/<source>tests/<source>\/home\/runner\/work\/{{cookiecutter.project_name}}\/{{cookiecutter.project_name}}\/tests/g" coverage.xml

      - name: SonarQube Cloud Scan
        env:
          SONAR_TOKEN: {{ "${{ secrets.SONAR_TOKEN }}" }}
        # No need to run SonarCloud analysis if dependabot update or token not defined
        if: env.SONAR_TOKEN != '' && (github.actor != 'dependabot[bot]')
        uses: SonarSource/sonarqube-scan-action@v5.2.0
