name: pre-commit
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
      - run: |
          pip install --constraint=${{ github.workspace }}/.github/workflows/constraints.txt pip
          pip install --constraint=${{ github.workspace }}/.github/workflows/constraints.txt pre-commit
      - name: Compute cache key prefix
        if: matrix.os != 'windows-latest'
        id: cache_key_prefix
        shell: python
        run: |
          import hashlib
          import subprocess
          import sys

          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = "${{ runner.os }}-{}-{}-pre-commit".format(python, digest)
          cmd = f'echo "result={result}" >> $GITHUB_OUTPUT'
          subprocess.run(cmd, shell=True)
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        if: matrix.os != 'windows-latest'
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.cache_key_prefix.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.cache_key_prefix.outputs.result }}-
      - run: pre-commit run --all-files --show-diff-on-failure --color=always
