name: Release Drafter
on:
  push:
    branches:
      - main

jobs:
  update_relase_draft:
    name: Update Release Draft
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
